FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

# Por defecto corre las pruebas unitarias con cobertura
CMD ["pnpm", "test:cov"]
