apiVersion: v1
kind: ConfigMap
metadata:
  name: deport-back-config
  namespace: deport-back
data:
  NODE_ENV: "production"
  PORT: "3000"
  # el Cloud SQL Auth Proxy corre como sidecar y escucha en localhost
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  DB_SSL: "false"
  # URLs públicas de las otras 2 APIs del seguimiento (no son secretas)
  API_FASTIFY_URL: "http://20.66.47.84"
  INVENTARIO_U_URL: "http://158.247.121.202"
  REDIS_HOST: "10.24.160.203"
  REDIS_PORT: "6379"
