apiVersion: v1
kind: Service
metadata:
  name: deport-back
  namespace: deport-back
  annotations:
    # shape flexible 10Mbps: el único Load Balancer que entra en Always Free
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
spec:
  type: LoadBalancer
  selector:
    app: deport-back
  ports:
    - port: 80
      targetPort: 3000
